// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG0YLZtYNRx-lieDxrVTnnmk6SWGwjaSo',
    appId: '1:436727063815:web:0fd8ee52d0e167c8c4d1a2',
    messagingSenderId: '436727063815',
    projectId: 'bigmart-982b3',
    authDomain: 'bigmart-982b3.firebaseapp.com',
    storageBucket: 'bigmart-982b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIXuUsKQi6eRvi3OHvXP-Y80b01iuijtc',
    appId: '1:436727063815:android:9c8fada6139b78f1c4d1a2',
    messagingSenderId: '436727063815',
    projectId: 'bigmart-982b3',
    storageBucket: 'bigmart-982b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXzfyPDUbZxjFLkwi66OZpto8x1u1nDFw',
    appId: '1:436727063815:ios:035229bf79b25ae4c4d1a2',
    messagingSenderId: '436727063815',
    projectId: 'bigmart-982b3',
    storageBucket: 'bigmart-982b3.appspot.com',
    iosBundleId: 'com.example.bigmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXzfyPDUbZxjFLkwi66OZpto8x1u1nDFw',
    appId: '1:436727063815:ios:2e06a5bf332ea34bc4d1a2',
    messagingSenderId: '436727063815',
    projectId: 'bigmart-982b3',
    storageBucket: 'bigmart-982b3.appspot.com',
    iosBundleId: 'com.example.bigmart.RunnerTests',
  );
}
